name: Hackintosh Kext Builder

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 22 * * *'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Install dependencies
      run: |
        brew install tree
        brew install gnu-sed
        brew install python3
        chmod +x build/*.sh
        chmod +x download/*.sh
    - name: Prepare enviroment
      run: |
        echo $GITHUB_WORKSPACE
        ls -n /Applications/ | grep Xcode*
        sudo xcode-select -r
        mkdir -p deploy
    - name: Build Nightly Kext
      run: |
        for f in build/*.sh; do
          bash "$f" || break
        done
    - name: Download Files
      run: |
        for f in download/*.sh; do
          bash "$f" || break
        done
    - name: Generate HTML
      run: |
        cd $GITHUB_WORKSPACE
        DATE="$(echo $(TZ=UTC-8 date '+%Y-%m-%d %H:%M:%S'))"
        cp -rf src/* deploy/
        cd deploy/
        sudo find . -name ".DS_Store" -exec rm -r {} \;
        python3 ../util/tree.py
    - name: Deploy
      run: |
        cd $GITHUB_WORKSPACE
        mkdir ./public-git
        cd ./public-git
        git init
        git config --global user.email "${GIT_EMAIL}"
        git config --global user.name "${GIT_USERNAME}"
        git remote add origin ${REMOTE_REPO}
        git checkout -b master
        cp -rf $GITHUB_WORKSPACE/deploy/* ./
        git add --all .
        DATE="$(echo $(TZ=UTC-8 date '+%Y-%m-%d %H:%M:%S'))"
        git commit -m "Deploy: $DATE"
        git push --quiet --force origin HEAD:master
      env:
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
        REMOTE_REPO: ${{ secrets.REMOTE_REPO }}
