name: Hackintosh Kext Builder

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 22 * * *'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Install dependencies
      run: |
        brew install tree
        brew install gnu-sed
        chmod +x build/*.sh
    - name: Prepare enviroment
      run: |
        echo $GITHUB_WORKSPACE
        ls -n /Applications/ | grep Xcode*
        sudo xcode-select -r
        mkdir -p deploy
    - name: Build Lilu
      run: bash ./build/Lilu.sh
    - name: Build WhateverGreen
      run: bash ./build/WhateverGreen.sh
    - name: Build VirtualSMC
      run: bash ./build/VirtualSMC.sh
    - name: Build AppleALC
      run: bash ./build/AppleALC.sh
    - name: Build AirportBrcmFixup
      run: bash ./build/AirportBrcmFixup.sh
    - name: Build BrcmPatchRAM
      run: bash ./build/BrcmPatchRAM.sh
    - name: Build AppleIntelWifiAdapter
      run: bash ./build/AppleIntelWifiAdapter.sh
    - name: Build OS-X-USB-Inject-All
      run: bash ./build/OS-X-USB-Inject-All.sh
    - name: Generate HTML
      run: |
        cd $GITHUB_WORKSPACE
        DATE="$(echo $(TZ=UTC-8 date '+%Y-%m-%d %H:%M:%S'))"
        cp -rf src/* deploy/
        cd deploy/
        tree --prune -H '.' -L 4 --noreport --charset utf-8 -P "*.zip" > index.html
        gsed -i 's|<title>Directory Tree</title>|<title>黑苹果 常用 Kext 下载站（每日构建） \| Sukka</title>|g' ./index.html
        gsed -i 's|<h1>Directory Tree</h1>|<h1>黑苹果 常用 Kext 下载站（每日构建）</h1>|g' ./index.html
        gsed -i 's|<a href=".">.</a><br>|<p>最后更新于 {{DATE}}</p><br><a href="/">https://kext.skk.moe</a><br>|g' ./index.html
        gsed -i "s|{{DATE}}|$DATE|g" ./index.html
        gsed -i 's|<p class="VERSION">|<p class="VERSION"><strong style="font-size:120%">Made by <a href="https://skk.moe">Sukka</a> with Love<br></strong>|g' ./index.html
    - name: Deploy
      run: |
        cd $GITHUB_WORKSPACE
        mkdir ./public-git
        cd ./public-git
        git init
        git config --global push.default matching
        git config --global user.email "${GIT_EMAIL}"
        git config --global user.name "${GIT_USERNAME}"
        git remote add origin ${REMOTE_REPO}
        git checkout -b master
        cp -rf $GITHUB_WORKSPACE/deploy/* ./
        git add --all .
        DATE="$(echo $(TZ=UTC-8 date '+%Y-%m-%d %H:%M:%S'))"
        git commit -m "Deploy: $DATE"
        git push --quiet --force origin HEAD:master
      env:
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
        REMOTE_REPO: ${{ secrets.REMOTE_REPO }}
