name: Hackintosh Kext Builder

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 22 * * *'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: List & Rest Xcode
      run: |
        echo $GITHUB_WORKSPACE
        brew install tree
        brew install gnu-sed
        ls -n /Applications/ | grep Xcode*
        sudo xcode-select -r
        mkdir -p deploy
    - name: Build Lilu
      run: |
        git clone https://github.com/acidanthera/Lilu.git --depth=10 && cd Lilu
        xcodebuild -configuration Debug > /dev/null 2>&1 ;
        xcodebuild -configuration Release > /dev/null 2>&1 ;
        cd ..
        cp Lilu/build/*/*.zip deploy/
    - name: Build WhateverGreen
      run: |
        git clone https://github.com/acidanthera/WhateverGreen.git --depth=10 && cd WhateverGreen
        src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/Lilu/master/Lilu/Scripts/bootstrap.sh) && eval "$src" > /dev/null 2>&1 || exit 1
        xcodebuild -configuration Debug > /dev/null 2>&1 ;
        xcodebuild -configuration Release > /dev/null 2>&1 ;
        cd ..
        cp WhateverGreen/build/*/*.zip deploy/
    - name: Build VirtualSMC
      run: |
        git clone https://github.com/acidanthera/VirtualSMC.git --depth=10 && cd VirtualSMC
        src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/Lilu/master/Lilu/Scripts/bootstrap.sh) && eval "$src" > /dev/null 2>&1 || exit 1
        xcodebuild -target Package -configuration Debug > /dev/null 2>&1 ;
        xcodebuild -target Package -configuration Release > /dev/null 2>&1 ;
        cd ..
        cp WhateverGreen/build/*/*.zip deploy/
    - name: Build AppleALC
      run: |
        git clone https://github.com/acidanthera/AppleALC.git --depth=10 && cd AppleALC
        src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/Lilu/master/Lilu/Scripts/bootstrap.sh) && eval "$src" > /dev/null 2>&1 || exit 1
        xcodebuild -configuration Debug > /dev/null 2>&1 ;
        xcodebuild -configuration Release > /dev/null 2>&1 ;
        cd ..
        cp AppleALC/build/*/*.zip deploy/
    - name: Build AirportBrcmFixup
      run: |
        git clone https://github.com/acidanthera/AirportBrcmFixup.git --depth=10 && cd AirportBrcmFixup
        src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/Lilu/master/Lilu/Scripts/bootstrap.sh) && eval "$src" > /dev/null 2>&1 || exit 1
        xcodebuild -configuration Debug > /dev/null 2>&1 ;
        xcodebuild -configuration Release > /dev/null 2>&1 ;
        cd ..
        cp AirportBrcmFixup/build/*/*.zip deploy/
    - name: Build BrcmPatchRAM
      run: |
        git clone https://github.com/acidanthera/BrcmPatchRAM.git --depth=10 && cd BrcmPatchRAM
        xcodebuild -configuration Debug -scheme BrcmPatchRAM > /dev/null 2>&1 ;
        cd build/Products/Debug
        zip -qry BrcmPatchRAM-$(cat ../../../BrcmPatchRAM.xcodeproj/project.pbxproj | grep -i 'CURRENT_PROJECT_VERSION' | head -1 | grep -oE '\d\.\d\.\d')-DEBUG.zip *.kext
        cd -
        xcodebuild -configuration Release -scheme BrcmPatchRAM > /dev/null 2>&1 ;
        cd build/Products/Release
        zip -qry BrcmPatchRAM-$(cat ../../../BrcmPatchRAM.xcodeproj/project.pbxproj | grep -i 'CURRENT_PROJECT_VERSION' | head -1 | grep -oE '\d\.\d\.\d')-RELEASE.zip *.kext
        cd $GITHUB_WORKSPACE
        cp BrcmPatchRAM/build/Products/*/*.zip deploy/
    - name: Build OS-X-USB-Inject-All
      run: |
        git clone https://github.com/Sniki/OS-X-USB-Inject-All.git --depth=10 && cd OS-X-USB-Inject-All
        make clean
        make all > /dev/null 2>&1 ;
        make distribute
        cp Distribute/*.zip $GITHUB_WORKSPACE/deploy/
    - name: Generate HTML
      run: |
        cd $GITHUB_WORKSPACE
        cp -rf src/* deploy/
        cd deploy/
        tree --prune -H '.' -L 2 --noreport --charset utf-8 -P "*.zip" > index.html
        gsed -i 's|<title>Directory Tree</title>|<title>黑苹果 常用 Kext 下载站（每日构建） \| Sukka</title>|g' ./index.html
        gsed -i 's|<h1>Directory Tree</h1>|<h1>黑苹果 常用 Kext 下载站（每日构建）</h1>|g' ./index.html
        gsed -i 's|<a href=".">.</a><br>|<p>所有文件均由下列 GitHub 仓库 master 分支的最新代码、使用 GitHub Actions 和 Xcode 11 每日构建</p><ul><li><a href="https://github.com/acidanthera/AirportBrcmFixup" target="_blank" rel="noreferrer nofollow noopener">AirportBrcmFixup @ GitHub</a></li><li><a href="https://github.com/acidanthera/AppleALC" target="_blank" rel="noreferrer nofollow noopener">AppleALC @ GitHub</a></li><li><a href="https://github.com/acidanthera/BrcmPatchRAM" target="_blank" rel="noreferrer nofollow noopener">BrcmPatchRAM @ GitHub</a></li><li><a href="https://github.com/acidanthera/Lilu" target="_blank" rel="noreferrer nofollow noopener">Lilu @ GitHub</a></li><li><a href="https://github.com/Sniki/OS-X-USB-Inject-All" target="_blank" rel="noreferrer nofollow noopener">USBInjectAll @ GitHub</a></li><li><a href="https://github.com/acidanthera/WhateverGreen" target="_blank" rel="noreferrer nofollow noopener">WhateverGreen @ GitHub</a></li></ul><a href="/">https://kext.skk.moe</a><br>|g' ./index.html
    - name: Deploy
      run: |
        cd ..
        mkdir ./public-git
        cd ./public-git
        git init
        git config --global push.default matching
        git config --global user.email "${GIT_EMAIL}"
        git config --global user.name "${GIT_USERNAME}"
        git remote add origin ${REMOTE_REPO}
        git checkout -b master
        cp -rf ../deploy/* ./
        git add --all .
        DATE="$(echo $(TZ=UTC-8 date '+%Y-%m-%d %H:%M:%S'))"
        git commit -m "Deploy: $DATE"
        git push --quiet --force origin HEAD:master
      env:
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
        REMOTE_REPO: ${{ secrets.REMOTE_REPO }}